### ISSUE TITLE
Feature Suggestion: Retrieving Value from `position` Property

### ISSUE THREAD

**Issue by SterlingButters** [xhlulu/dash-draggable#3]
It appears that `callback`'s to the`position` property only allow you to set the property with position data, not retrieve position data. This could be very useful in the following example:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/22737286/52819727-13542080-3078-11e9-8984-204e8d329cda.gif)

You can see that it would be useful here to create a callback that stores the last 2 positions and makes a comparison and if `position_before` != `position_after` then the button logic is ignored.

Also I plan to create a callback between a `Store` component and the `Position` property of this component so that even if the user exits the app, their layout remains the same.

**Comment by xhluca** [comment]
That would be interesting. I think that you can probably use the `onDrag` event listener and update `dash_draggable`'s position prop using the `position` prop from `Draggable`.

Check out the react-draggable docs here: https://www.npmjs.com/package/react-draggable

Feel free to open a PR if you feel this would be a good addition!

**Comment by SterlingButters** [comment]
@xhlulu Hoping you might take a look at my branch [JSON Cycle Error](https://github.com/SterlingButters/dash-draggable/tree/dev) I feel like everything is set up right. I'm brand new to react so I've never seen this error before and I don't know how to resolve it.

<img width="522" alt="screen shot 2019-02-14 at 11 03 33 pm" src="https://user-images.githubusercontent.com/22737286/52833874-fa199700-30ac-11e9-8e8b-efb89a117041.png">

The goal is to get `DeltaX` and `DeltaY` to use these for the comparison 

UPDATE: 
Interesting... I just realized that I probably want to use the `onStop` property instead of the `onDrag` but I really get an odd result - the element is "stuck" to the mouse... And the JSON error is still there too -.- what is going on...

**Comment by xhluca** [comment]
https://github.com/SterlingButters/dash-draggable/blob/da870d076012627b3558f051dec93bfc07373cdc/src/lib/components/dash_draggable.react.js#L16-L20

I believe that the `node` property of `data` here is not JSON serializable... which means it can't be passed to setProps. Could you try to just pass everything except `node`, and construct a new object that is passed to setProps? E.g.

```javascript
this.props.setProps({
  lastX: data.lastX,
  lastY: data.lastY,
  ...
})
```

**Comment by SterlingButters** [comment]
Great suggestion! Let me try that out! Still new but taking notes as I go!

UPDATE:
IT WORKS! Awesome! I'll fix it up nice and submit a PR

Just a side question: If `node` is not JSON serializable, how can `children` be of PropType `node`

**Comment by SterlingButters** [comment]
Also, interestingly, `deltaX` and `deltaY` are always returning 0. Not sure why -  this is in the `console.log` __before__ setting them as props so idk 

UPDATE:
Think I got it

**Comment by SterlingButters** [comment]
@xhlulu So sorry, I meant to merge that last PR to my own fork first - I wanted you to review before I merged - good news is it works haha I'll just delete my fork so I don't do that again

**Comment by xhluca** [comment]
This if fine! Feel free to close this issue if there isn't more to update :)
