### ISSUE TITLE
Error Loading Dependencies

### ISSUE THREAD

**Issue by SterlingButters** [xhlulu/dash-draggable#5]
@xhlulu So I just deleted my fork from which I made the last PR and then I cloned from here and I get `Error Loading Dependencies` in the browser! 

js console gives me:
TypeError: undefined is not an object (evaluating 'n.subscribe')

I have a feeling its something wrong in the environment. 

Once cloned:

```
npm install

python -m venv venv
```

Isn't that all? I'm worried now that the PR may have done something but going through the diff, everything looks right like it did when it was working - can you confirm?

UPDATE:
It appears, interestingly enough, that its failing due to `dash-daq`... Which is so odd because it had just worked moments ago. Perhaps a bug in `dash-daq`? Tarballing dist and using outside environment results in no conflict - I wonder whats up

**Comment by xhluca** [comment]
Definitely pretty odd. Maybe try to isolate the error without dash-draggable, and if it's only caused by dash-daq it might be a good idea to open an issue in the dash-daq repo!

**Comment by SterlingButters** [comment]
I opened an issue there. Are you experiencing the same issue? Wondering if I can isolate to just my system.

**Comment by xhluca** [comment]
I haven't had the time to try it out! I'd recommend you to try to create a new venv for that to see if it works

**Comment by SterlingButters** [comment]
Yeah tried that already. However! if I change my python interpreter to my regular Anaconda in my IDE it works! But obviously need the venv for dev... Truly odd...

**Comment by xhluca** [comment]
That's really weird... In this case try to run `virtualenv venv` instead, let's see if this one works better.

**Comment by xhluca** [comment]
Make sure to correctly activate your virtual environment!

**Comment by SterlingButters** [comment]
same result with `virtualenv venv` - environment was activated for both `venv` and `virtualenv`

**Comment by xhluca** [comment]
Hmm pretty weird... I'll try to reproduce this when I get some time! Lmk in the meantime if you have any update :)

**Comment by SterlingButters** [comment]
Decided to try and work up my `dcc.Store` example but `dcc.Store` isn't working either... It doesn't throw the `Failed to Load Dependency Error` but on a refresh, it definitely "erases" the data in the `dcc.Store` for both `storage_type='session'` and `storage_type='local'` - definitely not the anticipated behavior, wondering if its related

**Comment by SterlingButters** [comment]
Thank God: 

https://github.com/plotly/dash-daq/issues/32:
> @SterlingButters Thanks for submitting this -- we're getting issues with the NPM package. I would recommend downgrading to `0.1.1` ([#25 (comment)](https://github.com/plotly/dash-daq/issues/25#issuecomment-464796147)). Sorry for the inconvenience.

Going to leave this issue open still as I haven't checked with a downgrade of `daq`

**Comment by SterlingButters** [comment]
It was an issue with `dash-daq` - phew...
